
# enter the address to reach the spinnaker (gate) api
# 
# Your Spinnaker operator should know what this address is and it would probably look something like...
#   gate.spinnaker.yourcompany.com or spinnaker-api.yourcompany.com
# 
# 
spinnakerApiAddress: api.spin.armory.io
# 
#
# ==========================================================
#  * * *  Override Default Configurations * * *
# ==========================================================
# 
# Uncomment the following line and change it if you need to override the webhook configuration
# defaultWebhookPath: webhooks/git/github
# 
# Uncomment the following line and change it if the dinghyfile name is different i.e. Spinnakerfile
# dinghyfileName: dinghyfile
# 
# Uncomment the following line and change it if you need to use a different schema
# defaultWebhookSchema: https
# 
# 
# ==========================================================
#  * * *  Preconfigured Repositories * * *
# ==========================================================
# 
# If your organization already has a repository that has the appropriate configuration already setup then comment 
#  out the spinnakerApiAddress line and uncomment and modify one of the _extends lines below
# 
# You can reference another repo inside your org like this...
# _extends: another-repo
# 
# You can reference another repo in another org like this...
# _extends: another-org/another-repo
#
# 
